### ISSUE TITLE
Focus problem

### ISSUE THREAD

**Issue by enderahmetyurt** [edisdev/vue-datepicker-ui#1]
Datepicker tiplerine tıklayınca bir digeri kapanmıyor. Sayfa yana doğru genişliyor.

<img width="1629" alt="screen shot 2018-12-31 at 09 10 37" src="https://user-images.githubusercontent.com/447588/50555364-2a170180-0cdc-11e9-9f6d-08427f5bc530.png">
<img width="1475" alt="screen shot 2018-12-31 at 09 10 43" src="https://user-images.githubusercontent.com/447588/50555365-2a170180-0cdc-11e9-8eb5-b94476bc85f9.png">

**Comment by SerkanSipahi** [comment]
@enderahmetyurt could please describe you issue/problem in english please, thanks.

**Comment by enderahmetyurt** [comment]
Sure.

When I click a a datepicker without close open one they are overlapped. I guess when a datepicker clicked open one datepicker should be closed.

The second problem is enlarging. When clicking a datepicker which is the rightest one page is extending to right. you can see it from the second image.
