### ISSUE TITLE
Incorrect number of days in December 2020

### ISSUE THREAD

**Issue by mcndit** [edisdev/vue-datepicker-ui#21]
There's no 31st of December 2020

**Comment by mcndit** [comment]
I guess this bug is related to the leap year.

**Comment by edisdev** [comment]
Hi 🖐 Thank you for issue, this issue has been fixed in new version (0.1.3) at today 🙏

**Comment by edisdev** [comment]
Fixed commit : https://github.com/edisdev/vue-datepicker-ui/commit/069dcdf547da8859796f294b9c42899d9d3d6152
