### ISSUE TITLE
Suggestion: close on select

### ISSUE THREAD

**Issue by stefandevo** [edisdev/vue-datepicker-ui#3]
How about an option to close the popup when selecting a date?

**Comment by rottmann** [comment]
Currently you can fake it, but i hope the author will implement options for an easier usage.

```
<calendar
  v-model="calendar.value"
  ...
  v-on:input="calendarChange"
  inputClass="calendar-input"
></calendar>
```

```
  data() {
    return {
      calendar: {
        'value': new Date()
      },
      calendarFirstCall: true
    }
  },

  methods: {
    calendarChange: function() {
      // not show the calendar on the first view
      if (this.calendarFirstCall) {
        this.calendarFirstCall = false
        return
      }
      let evt = new MouseEvent('click', {
        bubbles: true,
        cancelable: true,
        view: window
      })
      let elements = document.getElementsByClassName('calendar-input')
      elements[0].dispatchEvent(evt)
    }
  }
```

**Comment by edisdev** [comment]
> Currently you can fake it, but i hope the author will implement options for an easier usage.

Thank you 👍II will make this property with together new feature at near time.

**Comment by nezaboravi** [comment]
Did near time close? :) its a year and half :)

**Comment by edisdev** [comment]
Sorry, This problem has been resolved albeit late .
Thanks 🙏

**Comment by edisdev** [comment]
Fixed commit: https://github.com/edisdev/vue-datepicker-ui/commit/4cd2c7fece8132ae33ad4c2c09ead0ffb88dc4f6
