### ISSUE TITLE
github.io/vue-datepicker-ui sayfası

### ISSUE THREAD

**Issue by sevkioruc** [edisdev/vue-datepicker-ui#46]
Selam :) https://edisdev.github.io/vue-datepicker-ui/ sayfası 404 dönüyor

**Comment by edisdev** [comment]
Selam :) Vue 3 için destek ekledim, dökümantasyonu bu versiyonu yayına almadan göndermiş oldum. Ondan dolayı iptal etmiştim sayfayı. Şimdi yayında :) Teşekkürler :)
