### ISSUE TITLE
Firing events

### ISSUE THREAD

**Issue by kyoukhana** [edisdev/vue-datepicker-ui#49]
I don't see a example on how you can fire events

if i do this

```
<Datepicker range v-model="selectedDate" lang="en" @reset='clearCalendar()'/>
```

reset doesn't get fired.  Please let me know if I am missing something

**Comment by edisdev** [comment]
Hi @kyoukhana ✋🏻 The reset event works with the clear button. So, value of `show-clear-button` property should be true.

Source: [Show Clear Button Prop](https://edisdev.github.io/vue-datepicker-ui/props.html#showclearbutton)

**Comment by kyoukhana** [comment]
```
	<Datepicker range v-model="selectedDate" lang="en" show-clear-button='true' @reset='clearCalendar()'/>
	```

Awesome this worked
