### ISSUE TITLE
2-way-databinding not work

### ISSUE THREAD

**Issue by rottmann** [edisdev/vue-datepicker-ui#5]
example:

```
<datepicker v-model="date" :lang="datePicker.lang" :date-format="datePicker.dateFormat"></datepicker>

...

  data() {
    return {
      date: '01.01.2019',
      datePicker: {
        'lang': 'de',
        'dateFormat': {
          'day': '2-digit',
          'month': '2-digit',
          'year': 'numeric'
        }
      }
    }
  },

  mounted() {
    setTimeout(function() {
      this.date = '31.12.2018'
    }, 1000)
  },
```

The Inputfield still shows '01.01.2019' after the timeout.
When you open the datepicker Jan 2019 is visible, it better should show Dec 2018.

**Comment by rottmann** [comment]
Or could you implement a method to update the value from outside the component?

E.g. important when load a recordset with a date from a server, which need some time to respond. Currently i must prevent datepicker-rendering with v-if, but the value can only be change once with v-if.

**Comment by edisdev** [comment]
Hi 🖐

I made an improvement for this problem.

Thanks 🙏

**Comment by edisdev** [comment]
Fixed commit: https://github.com/edisdev/vue-datepicker-ui/commit/4cd2c7fece8132ae33ad4c2c09ead0ffb88dc4f6
