### ISSUE TITLE
Doesnʼt update values on emit and doesnʼt pass the initial value

### ISSUE THREAD

**Issue by yukal** [edisdev/vue-datepicker-ui#59]
Hi! I'm trying to use Datepicker with custom filter parameters, without using v-model. But it doesn't work, it even doesn't set the initial value.

```js
import { onMounted, ref } from 'vue';
import VueDatepickerUi from 'vue-datepicker-ui';

var date = ref(new Date());

onMounted(() => {
  console.log('onMounted', date.value);
});

function update(date) {
  date.value = date;
  console.log(date);
}

function toISODate(date) {
  return date.toISOString().slice(0, 10);
}
```

```vue
<template>
  <div>
    <p>{{ toISODate(date) }}</p>
    <p>
      <VueDatepickerUi lang="en" :value="date" @change="update" />
    </p>
    <p>
      <VueDatepickerUi lang="en" :value="date" update:modelValue="update" />
    </p>
  </div>
</template>
```

I've found different code solutions.
This is what I have after the install via npm `npm install vue-datepicker-ui@vue3 --save`:

```js
emitInputAction: function emitInputAction() {
      if (JSON.stringify(this.modelValue) !== this.selectedDate) {
        this.$emit('update:modelValue', this.selectedDate);
      }
      // other code ...
    },
```

And this is how it looks at the last (8d1005be7b32427d807a48d78db53836ad342829) commit:
https://github.com/edisdev/vue-datepicker-ui/blob/8d1005be7b32427d807a48d78db53836ad342829/lib/vuedatepickerui.umd.js#L2582

You can check my example at the stackblitz.com:
https://stackblitz.com/edit/vitejs-vite-dhczkx?file=src%2FApp.vue

**Comment by edisdev** [comment]
Hello 🖐

This component is processed with "model-value" data. And the `update:modelValue` emit event doesn't work either. 
Because it should work as `@update:modelValue`.

I edited the example on Stackblitz.com. https://stackblitz.com/edit/vitejs-vite-eae1wx?file=src%2FApp.vue

I hope this edit solves your problem :)

**Comment by yukal** [comment]
@edisdev Ok, now it set the initial value with `model-value` attribute, but it still doesn't emit `@update:modelValue` event even with `@` symbol.

```vue
<VueDatepickerUi lang="en" :model-value="date" @update:modelValue="update" />
```

Please check your `update model value` version on the Stackblitz, it still doesn't change the value.
The ISO date (above the date picker) should have changed, but it hasn't.

**Comment by edisdev** [comment]
@yukal Yes, I see issue now. As far as I see, the issue is related to the conflict in the `date` variable name :)


Please, can you check link ? 😊 https://stackblitz.com/edit/vitejs-vite-wrkcvw?file=src%2FApp.vue

**Comment by yukal** [comment]
Oh, 🤦 how did I not notice this? 😂
@edisdev Sorry for bothering you for no reason, and thanks for your help :)
